#!/bin/sh
EX_IFACE="wlan0"
IN_IFACE="enp4s0"
INTRANET="192.168.2.0/24"

#nat dns requests to Tor
iptables -t nat -A OUTPUT -d 127.0.0.1/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -i $IN_IFACE -p udp --dport 53 -j REDIRECT --to-ports 53

# Con ACCEPT evitamos que salga por TOR el trafico en los puertos elegidos
# iptables -t nat -A PREROUTING -i $IN_IFACE -p tcp --syn -m multiport --dports 3142,81 -j ACCEPT

# Todo el trafico restante tcp va por tor al 9040
iptables -t nat -A PREROUTING -i enp4s0 -p tcp --syn -j REDIRECT --to-ports 9040

service tor restart
#service dnsmasq restart
#service dnscrypt-proxy restart

