#!/bin/sh
#EX_IFACE="wlan0"
#IN_FACE="enp4s0"
#INTRANET="192.168.2.0/24"
#GATEWAYIP="192.168.1.1"
#ANYWHERE="any/0"

BANNED_IPS="./banlist.txt"

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
# Politicas por defecto
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

# echo 1 > /proc/sys/net/ipv4/ip_forward 
# /etc/sysctl.conf, asegurándonos de que exista una línea como: net.ipv4.ip_forward=1
#MASQUERADE podría funcionar también si la dirección IP de eth0 fuese estática, pero recomienda utilizar SNAT.
#iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -o eth0 -j SNAT --to 80.58.1.14
iptables -t nat -A POSTROUTING -o $EX_IFACE -j MASQUERADE
route add default gw $GATEWAYIP $EX_IFACE
# Con la linea anterior ya establecemos la ruta por defecto, pero en ocasiones me ha fallado ¿? 
# Es redundante para establecer la ruta por defecto ...
ip route replace default via $GATEWAYIP
#LAN destinations that shouldn't be routed through Tor
#Check reserved block.
_non_tor="127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
#Other IANA reserved blocks (These are not processed by tor and dropped by default)
_resv_iana="0.0.0.0/8 100.64.0.0/10 169.254.0.0/16 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 198.18.0.0/15 198.51.100.0/24 203.0.113.0/24 224.0.0.0/3"


for _lan in $_non_tor; do
 iptables -t nat -A OUTPUT -d $_lan -j RETURN
 iptables -t nat -A PREROUTING -i $IN_IFACE -d $_lan -j ACCEPT
done

for _iana in $_resv_iana; do
 iptables -t nat -A OUTPUT -d $_iana -j RETURN
 iptables -t nat -A PREROUTING -i $IN_IFACE -d $_iana -j ACCEPT
done

# Bloquea entrada y forward de IP's
for i in `cat $BANNED_IPS`; do

        iptables -I INPUT -s $i -j DROP
        iptables -I OUTPUT -s $i -j DROP
        iptables -I FORWARD -s $i -j DROP
done

# Trafico ilimitado con la interface de bucle invertido
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
# Trafico ilimitado con el router
iptables -A INPUT -i  $EX_IFACE -s $GATEWAYIP -j ACCEPT
iptables -A OUTPUT -o $EX_IFACE -d $GATEWAYIP -j ACCEPT
# Open NTP como cliente
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A INPUT -p udp --sport 123 -j ACCEPT
# Y como server
iptables -A INPUT -p udp --dport 123 -j ACCEPT
iptables -A OUTPUT -p udp --sport 123 -j ACCEPT
iptables -A FORWARD -p udp --sport 123 -j ACCEPT
# Abrimos puertos 1-1024 a nuestra intranet 
iptables -A INPUT -i $IN_IFACE -s $INTRANET -j ACCEPT
iptables -A INPUT -s $ANYWHERE -p tcp --match multiport --dports 0:1023 -j DROP
iptables -A INPUT -s $ANYWHERE -p udp --match multiport --dports 0:1023 -j DROP
# Reject spoofed packets # These adresses are mostly used for LAN's, so if these would come to a WAN-only server, drop them.
iptables -A INPUT -i $EX_IFACE -s 10.0.0.0/8 -j DROP
iptables -A INPUT -i $EX_IFACE -s 127.0.0.0/8 -j DROP
iptables -A INPUT -i $EX_IFACE -s 172.16.0.0/12 -j DROP
iptables -A INPUT -i $EX_IFACE -s 169.254.0.0/16 -j DROP
iptables -A INPUT -i $EX_IFACE -s 192.168.0.0/16 -j DROP
iptables -A FORWARD -i $EX_IFACE -s 192.168.0.0/16 -j DROP
iptables -A FORWARD -i $EX_IFACE -s 192.168.1.0/24 -j DROP
#Multicast-adresses.
iptables -A INPUT -i $EX_IFACE -s 224.0.0.0/4 -j DROP
iptables -A INPUT -i $EX_IFACE -d 224.0.0.0/4 -j DROP
iptables -A INPUT -i $EX_IFACE -s 240.0.0.0/5 -j DROP
iptables -A INPUT -i $EX_IFACE -d 240.0.0.0/5 -j DROP
iptables -A INPUT -i $EX_IFACE -s 0.0.0.0/8 -j DROP
iptables -A INPUT -i $EX_IFACE -d 0.0.0.0/8 -j DROP
iptables -A INPUT -i $EX_IFACE -d 239.255.255.0/24 -j DROP
iptables -A INPUT -i $EX_IFACE -d 255.255.255.255 -j DROP
# Drop all invalid packets
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A FORWARD -m state --state INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j DROP
# Drop excessive RST packets to avoid smurf attacks
iptables -A INPUT -p tcp -m tcp --tcp-flags RST RST -m limit --limit 2/second --limit-burst 2 -j ACCEPT
# Don't allow pings through
iptables -A INPUT -p icmp --icmp-type 8 -m state --state NEW,ESTABLISHED,RELATED -j REJECT
iptables -A OUTPUT -p icmp --icmp-type 0 -m state --state ESTABLISHED,RELATED -j REJECT
# Borra todas las reglas y establece politica denegar ARP
arptables -F
arptables -P INPUT DROP
arptables -P OUTPUT DROP
# Solo permite ARP en la intranet y al Router
arptables -A INPUT -s $INTRANET -j ACCEPT
arptables -A INPUT -s $GATEWAYIP -j ACCEPT
arptables -A OUTPUT -d $INTRANET -j ACCEPT
arptables -A OUTPUT -d $GATEWAYIP -j ACCEPT

