#!/bin/sh
EX_IFACE="wlan0"
IN_IFACE="enp4s0"
INTRANET="192.168.2.0/24"

service tor stop

# Borra unas tablas 
iptables -t nat -D PREROUTING -i $IN_IFACE -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -D OUTPUT -d 127.0.0.1/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
# Borra la tabla -D que envia todo el trafico por tor
iptables -t nat -D PREROUTING -i $IN_IFACE -p tcp --syn -j REDIRECT --to-ports 9040
#iptables -t nat -D PREROUTING -p tcp --syn -j REDIRECT --to-ports 9040

